### ISSUE TITLE
RoBERTa evaluation on LAMA

### ISSUE THREAD

**Issue by AkariAsai** [facebookresearch/LAMA#28]
Thank you for open-sourcing and maintaining such a great project! :) 

I have an issue related to RoBERTa evaluation on LAMA. 
To evaluate the RoBERTa performance on LAMA, I downloaded RoBERTa {base,large} checkpoints from the [fairseq repository](https://github.com/pytorch/fairseq/tree/master/examples/roberta). Then I slightly modify [`run_experiment.py`](https://github.com/facebookresearch/LAMA/blob/master/scripts/run_experiments.py) to add RoBERTa to the target LMs as follows:

```py
LMs = [
    {
        "lm": "roberta",
        "label": "roberta",
        "models_names": ["roberta"],
        "roberta_model_name": "model.pt",
        "roberta_model_dir": "pre-trained_language_models/roberta.large/",
        "roberta_vocab_name": "dict.txt"
    }, ...
]
```
Although the RoBERTa large model is loaded correctly, many warnings show up saying that many words are not included `vocab_subset` in model.
```
2020-03-12 17:55:33,651 - LAMA - WARNING - word wingspan from vocab_subset not in model vocabulary!
2020-03-12 17:55:33,651 - LAMA - WARNING - word woken from vocab_subset not in model vocabulary!
2020-03-12 17:55:33,651 - LAMA - WARNING - word wooded from vocab_subset not in model vocabulary!
2020-03-12 17:55:33,651 - LAMA - WARNING - word wrestled from vocab_subset not in model vocabulary!
2020-03-12 17:55:33,651 - LAMA - WARNING - word wrinkled from vocab_subset not in model vocabulary!
2020-03-12 17:55:33,651 - LAMA - WARNING - word yanked from vocab_subset not in model vocabulary!
2020-03-12 17:55:33,651 - LAMA - WARNING - word yd from vocab_subset not in model vocabulary!
2020-03-12 17:55:33,651 - LAMA - WARNING - word yellowish from vocab_subset not in model vocabulary!
2020-03-12 17:55:33,651 - LAMA - WARNING - word yer from vocab_subset not in model vocabulary!
2020-03-12 17:55:33,651 - LAMA - WARNING - word zu from vocab_subset not in model vocabulary!
2020-03-12 17:55:33,651 - LAMA - WARNING - word zur from vocab_subset not in model vocabulary!
```
Then, it was terminated by the error shown below:
```
Traceback (most recent call last):
  File "scripts/run_experiments.py", line 221, in <module>
    run_all_LMs(parameters)
  File "scripts/run_experiments.py", line 214, in run_all_LMs
    run_experiments(*parameters, input_param=ip, use_negated_probes=False)
  File "scripts/run_experiments.py", line 135, in run_experiments
    Precision1 = run_evaluation(args, shuffle_data=False, model=model)
  File "/home/akari/projects/LAMA/scripts/batch_eval_KB_completion.py", line 390, in main
    model, data, vocab_subset, args.max_sentence_length, args.template
  File "/home/akari/projects/LAMA/scripts/batch_eval_KB_completion.py", line 233, in filter_samples
    if obj_label_ids:
RuntimeError: bool value of Tensor with more than one value is ambiguous
```
Do you have any insights into why many words are not found in `vocab_subset` and how we could solve the `RuntimeError`.

**Comment by fabiopetroni** [comment]
Hey @AkariAsai,

Unfortunately RoBERTa vocabulary is pretty different from the one we used in our paper - many words are not in the RoBERTa vocab.
Regarding the error, will push a fix soon .

Ciao,
Fabio

**Comment by fabiopetroni** [comment]
@AkariAsai this should fix the error https://github.com/facebookresearch/LAMA/commit/e702de7a0c0705b8ea02a2b69c8c35ac26764660

let me know

**Comment by AkariAsai** [comment]
Hi @fabiopetroni , thank you for your quick response! Regarding the error, I pulled and run the codes again but still get the same error. It seems that in some examples, the `obj_label_ids` are multiple tokens, not single token, and this might cause the error (maybe due to tokenization difference?).

```
obj_label_ids is tensor([8398])
obj_label_ids is tensor([7270])
obj_label_ids is tensor([10496])
obj_label_ids is tensor([1221])
obj_label_ids is tensor([3378])
obj_label_ids is tensor([8947])
obj_label_ids is tensor([10496])
obj_label_ids is tensor([  255, 25799,  8539])
Traceback (most recent call last):
  File "scripts/run_experiments.py", line 221, in <module>
    run_all_LMs(parameters)
  File "scripts/run_experiments.py", line 214, in run_all_LMs
    run_experiments(*parameters, input_param=ip, use_negated_probes=False)
  File "scripts/run_experiments.py", line 135, in run_experiments
    Precision1 = run_evaluation(args, shuffle_data=False, model=model)
  File "/home/akari/projects/LAMA/scripts/batch_eval_KB_completion.py", line 392, in main
    model, data, vocab_subset, args.max_sentence_length, args.template
  File "/home/akari/projects/LAMA/scripts/batch_eval_KB_completion.py", line 235, in filter_samples
    if obj_label_ids:
RuntimeError: bool value of Tensor with more than one value is ambiguous
```
I slightly modified the codes to filter out these examples, but it largely reduces the number of examples from the original LAMA dataset. e.g., Googe Re birth_place 2,937 -->  2404, which may not result in fair comparison with other LMs. 

We would really appreciate it if you help us to solve this issue!
